version: '3.7'

services:
  master:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-master
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: otus
      MYSQL_PASSWORD: otus
      MYSQL_ROOT_PASSWORD: 'otus'
    ports:
      - 3306:3306
    volumes:
      - mysql-master-db:/var/lib/mysql

  shard0:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-shard0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: otus
      MYSQL_PASSWORD: otus
      MYSQL_ROOT_PASSWORD: 'otus'
    ports:
      - 3330:3306
    volumes:
      - mysql-shard0:/var/lib/mysql

  shard1:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-shard1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: otus
      MYSQL_PASSWORD: otus
      MYSQL_ROOT_PASSWORD: 'otus'
    ports:
      - 3331:3306
    volumes:
      - mysql-shard1:/var/lib/mysql

  shard2:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-shard2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: otus
      MYSQL_PASSWORD: otus
      MYSQL_ROOT_PASSWORD: 'otus'
    ports:
      - 3332:3306
    volumes:
      - mysql-shard2:/var/lib/mysql

  shard3:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-shard3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: otus
      MYSQL_PASSWORD: otus
      MYSQL_ROOT_PASSWORD: 'otus'
    ports:
      - 3333:3306
    volumes:
      - mysql-shard3:/var/lib/mysql


volumes:
  mysql-master-db:
  mysql-shard0:
  mysql-shard1:
  mysql-shard2:
  mysql-shard3:


